CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR2(20) NOT NULL CONSTRAINT PRODUCT_PK PRIMARY KEY 
    , PRODUCT_NAME VARCHAR2(20) NOT NULL 
    , PRICE NUMBER NOT NULL 
    , PRODUCT_SIZE NUMBER NOT NULL 
    , STOCK NUMBER NOT NULL 
    , PRODUCT_GENDER VARCHAR2(20) NOT NULL
    , CATEGORY VARCHAR2(20) NOT NULL
);


CREATE TABLE MEMBER(
    ID VARCHAR2(20) CONSTRAINT USER_PK PRIMARY KEY,
    PASSWORD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    BIRTH DATE DEFAULT SYSDATE,
    GENDER NUMBER NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(20) NOT NULL,
    POINT VARCHAR2(20) NOT NULL,
    RANK VARCHAR2(20) NOT NULL
);

ALTER TABLE MEMBER ADD CARD_NUMBER VARCHAR2(20) NOT NULL;
ALTER TABLE MEMBER ADD CARD_PAYMENT VARCHAR2(20) NOT NULL;


CREATE TABLE BUY (
    ID NUMBER NOT NULL CONSTRAINT BUY_PK PRIMARY KEY
    , P_ID VARCHAR2(20) NOT NULL REFERENCES MEMBER (ID)
    , U_ID VARCHAR2(20) NOT NULL REFERENCES MEMBER (ID)
);

CREATE TABLE MANAGER (
    ID VARCHAR2(20) NOT NULL CONSTRAINT MANAGER_PK PRIMARY KEY 
    , PASSWORD VARCHAR2(20) NOT NULL 
    , NAME VARCHAR2(20) NOT NULL 
    , RANK VARCHAR2(20) NOT NULL 
);

CREATE TABLE PRODUCT_REVIEWS (
    ID NUMBER CONSTRAINT REVIEWS_PK PRIMARY KEY,
    PRO_ID VARCHAR2(20) CONSTRAINT PRODUCT_FK
    REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    CONTENT VARCHAR2(100),
    WRITER VARCHAR2(20) CONSTRAINT PRODUCT_FK2
    REFERENCES MEMBER(ID) ON DELETE CASCADE
);







